# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://www.joshwiegand.com"
build_search_index = false
compile_sass = false
minify_html = true
output_dir = "dist"

[extra]
name = "Josh Wiegand"
