# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://www.joshwiegand.com"
compile_sass = false
build_search_index = false
minify_html = false

[extra]
name = "Josh Wiegand"
